cache:
  directories:
    - pandoc_download
language: python
matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    # Travis doesn't support Python on OSX, so use generic
    - os: osx
      language: generic
addons:
  apt:
    packages:
      - pandoc
      - curl
      - jq
before_install:
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then .travis/macos_python.sh; . myenv/bin/activate; else .travis/install_pandoc.sh; export PATH=$TRAVIS_BUILD_DIR/pandoc/usr/bin:$PATH; pandoc --version; fi
  - .travis/install_jansson.sh
  - travis_retry pip install pytest>=2.7.3 --upgrade
script:
  - ./clone_avro_and_build.sh --static
  - ./run_benchmark.sh
deploy:
  provider: pypi
  user: byhiras
  password:
    secure: CfVBR3pgujGwx6mwsyzeu87cipl65/UIeePg2kFHlzPUjWw8Ob+224XGcwWeNxZnhahaYiwStZyE1Us/oKxpdJjKnH8k6WrOe/0AB3nPoYAlXnx1F+RfLOEw0QLYGfUDo8fXlkOkJ3SdzzUmgKgcupGtoHtMVkmdTUF0gxwDOoU=
  distributions: "sdist bdist_egg"
  on:
    tags: true
