language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install pytest>=2.7.3 --upgrade
script:
  - ./clone_avro_and_build.sh --static && ./run_benchmark.sh
deploy:
  provider: pypi
  user: byhiras
  password:
    secure: CfVBR3pgujGwx6mwsyzeu87cipl65/UIeePg2kFHlzPUjWw8Ob+224XGcwWeNxZnhahaYiwStZyE1Us/oKxpdJjKnH8k6WrOe/0AB3nPoYAlXnx1F+RfLOEw0QLYGfUDo8fXlkOkJ3SdzzUmgKgcupGtoHtMVkmdTUF0gxwDOoU=
  distributions: "sdist bdist_egg"
  on:
    tags: true
